version: "2"
services:
 web:
  build: .
  command: npm run start
  volumes:
   - .:/usr/app/
  ports:
   - "3000:3000"
  depends_on:
   - dbcra
   - mdbcra
  links:
   - dbcra
   - mdbcra

 #MySQL Service
 dbcra:
  image: mysql:5.7.22
  restart: unless-stopped
  tty: true
  ports:
   - "3306:3306"
  environment:
   MYSQL_DATABASE: node-complete
   MYSQL_ROOT_PASSWORD: nodecomplete
   SERVICE_TAGS: dev
   SERVICE_NAME: mysql
  volumes:
   - dbdata:/var/lib/mysql/
   - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

 #PHPMyAdmin Service
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - "8080:80"
  links:
   - dbcra
  environment:
   PMA_HOST: localhost
   PMA_PORT: 3306
   PMA_ARBITRARY: 1

 mdbcra:
  image: mongo
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: nodecomplete
  ports:
   - "27017:27017"

 mongo-express:
  image: mongo-express
  restart: always
  links:
   - mdbcra
  ports:
   - 8081:8081
  environment:
   ME_CONFIG_MONGODB_ADMINUSERNAME: root
   ME_CONFIG_MONGODB_ADMINPASSWORD: nodecomplete
   ME_CONFIG_MONGODB_SERVER: mdbcra

#Volumes
volumes:
 dbdata:
  driver: local
